sudo: false
language: cpp
dist: trusty

branches:
  only:
    - master
    - develop
    - /^feature\/.*$/
    - /^hotfix\/.*$/
    - /^release\/.*$/

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - gcc-multilib
            - valgrind
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        brew update;
    fi

install:
  - eval "${MATRIX_EVAL}"
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew install valgrind;
    fi

before_script:
  - echo ${CC}
  - echo ${CXX}
  - ${CXX} --version
  - export TESTPREFIX="runtest"
  - sh install_make.sh

script:
  - make CXX=${CXX} CC=${CC} DEBUGFLAGS="" OPTFLAGS=""
  - make test CXX=${CXX} CC=${CC} TESTPREFIX=${TESTPREFIX} DEBUGFLAGS="" OPTFLAGS=""
  - if [ "$CXX" == "g++-6" ] && [ "$TRAVIS_OS_NAME" != "osx" ]; then
      make test_address CXX=${CXX} CC=${CC} DEBUGFLAGS="" OPTFLAGS="" LDFLAGS="-pthread -latomic -fuse-ld=gold" TESTPREFIX=${TESTPREFIX} ;
      valgrind --track-origins=yes --leak-check=full ./${TESTPREFIX}
    else
      make test_address CXX=${CXX} CC=${CC} DEBUGFLAGS="" OPTFLAGS="" TESTPREFIX=${TESTPREFIX} ;
    fi
#  - valgrind --track-origins=yes --leak-check=full ./${TESTPREFIX}