sudo: false
language: cpp
dist: trusty

branches:
  only:
    - master
    - develop
    - /^feature\/.*$/
    - /^hotfix\/.*$/
    - /^release\/.*$/

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - gcc-multilib
            - valgrind
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update;
      brew install valgrind;
    fi

before_script:
  - echo ${CC}
  - echo ${CXX}
  - ${CXX} --version
  - export TESTPREFIX="runtest"
  - sh install_make.sh

script:
  - make CXX=${CXX} CC=${CC}
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        make test CXX=${CXX} CC=${CC} TESTPREFIX=${TESTPREFIX};
        make test_address CXX=${CXX} CC=${CC} TESTPREFIX=${TESTPREFIX};
        valgrind --track-origins=yes --leak-check=full ./${TESTPREFIX};
    fi